# Generated by Django 3.0.3 on 2022-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spokenlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(default='en', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creation_language',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'creation_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialCommonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.CharField(max_length=255)),
                ('slide_status', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(max_length=255)),
                ('code_status', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.CharField(max_length=255)),
                ('assignment_status', models.PositiveSmallIntegerField(default=0)),
                ('prerequisite_status', models.PositiveSmallIntegerField(default=0)),
                ('additional_material', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_material_status', models.PositiveSmallIntegerField(default=0)),
                ('keyword', models.TextField()),
                ('keyword_status', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creation_tutorialcommoncontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creation_tutorialdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.TextField()),
                ('outline_status', models.PositiveSmallIntegerField(default=0)),
                ('script', models.URLField(max_length=255)),
                ('script_status', models.PositiveSmallIntegerField(default=0)),
                ('timed_script', models.URLField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('video_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('playlist_item_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('video_thumbnail_time', models.TimeField(default='00:00:00')),
                ('video_status', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'creation_tutorialresource',
                'managed': False,
            },
        ),
    ]
