# Generated by Django 3.0.3 on 2022-07-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spokenlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpFossSuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FOSS Category',
                'verbose_name_plural': 'FOSS Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpokenFoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(max_length=2)),
                ('is_learners_allowed', models.BooleanField(default=0, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_on_homepage', models.PositiveSmallIntegerField(default=0, help_text='0:Series, 1:Display on home page, 2:Archived')),
                ('available_for_nasscom', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for nasscom')),
                ('available_for_jio', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for jio, csc and spoken-tutorial.in')),
                ('csc_dca_programme', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for csc-dca programme')),
                ('category', models.ManyToManyField(to='spokenlogin.SpFossSuperCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spokenlogin.SpokenUser')),
            ],
            options={
                'verbose_name': 'FOSS',
                'verbose_name_plural': 'FOSSes',
                'ordering': ('foss',),
            },
        ),
    ]
