# Generated by Django 3.0.3 on 2022-07-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spokenlogin', '0002_spfosssupercategory_spokenfoss'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spfosssupercategory',
            table='creation_fosssupercategory',
        ),
        migrations.AlterModelTable(
            name='spokenfoss',
            table='creation_fosscategory',
        ),
    ]
