# Generated by Django 3.0.3 on 2022-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('logo', models.FileField(upload_to='brochures')),
                ('type', models.CharField(choices=[('JOB', 'JobFair'), ('INTERN', 'Internship')], default='JOB', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Event',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ers_Event',
        ),
    ]
