# Generated by Django 3.0.3 on 2022-01-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ers', '0002_auto_20220110_2255'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='emp_event',
        ),
    ]
