# Generated by Django 3.0.3 on 2022-01-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ers', '0003_auto_20220110_2257'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
    ]
