# Generated by Django 3.0.3 on 2022-06-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ers', '0004_auto_20220110_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title of the job page')),
                ('designation', models.CharField(max_length=250, verbose_name='Designation (Job Position)')),
                ('state_job', models.IntegerField()),
                ('city_job', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ers.Company')),
            ],
        ),
    ]
