# Generated by Django 3.0.3 on 2022-09-28 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FossCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(max_length=2)),
                ('is_learners_allowed', models.BooleanField(default=0, max_length=2)),
                ('is_translation_allowed', models.BooleanField(default=0, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_on_homepage', models.PositiveSmallIntegerField(default=0, help_text='0:Series, 1:Display on home page, 2:Archived')),
                ('available_for_nasscom', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for nasscom')),
                ('available_for_jio', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for jio and spoken-tutorial.in')),
                ('csc_dca_programme', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for csc-dca programme')),
            ],
            options={
                'verbose_name': 'FOSS',
                'verbose_name_plural': 'FOSSes',
                'db_table': 'creation_fosscategory',
                'ordering': ('foss',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FossSuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FOSS Category',
                'verbose_name_plural': 'FOSS Categories',
                'db_table': 'creation_fosssupercategory',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(default='en', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creation_language',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('tutorial', models.CharField(max_length=200)),
                ('minute_range', models.CharField(max_length=10)),
                ('second_range', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'website_question',
                'get_latest_by': 'date_created',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialCommonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.CharField(max_length=255)),
                ('slide_status', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(max_length=255)),
                ('code_status', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.CharField(max_length=255)),
                ('assignment_status', models.PositiveSmallIntegerField(default=0)),
                ('prerequisite_status', models.PositiveSmallIntegerField(default=0)),
                ('additional_material', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_material_status', models.PositiveSmallIntegerField(default=0)),
                ('keyword', models.TextField()),
                ('keyword_status', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial Common Content',
                'db_table': 'creation_tutorialcommoncontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial Detail',
                'db_table': 'creation_tutorialdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorialResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline', models.TextField()),
                ('outline_status', models.PositiveSmallIntegerField(default=0)),
                ('script', models.URLField(max_length=255)),
                ('script_status', models.PositiveSmallIntegerField(default=0)),
                ('timed_script', models.URLField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('video_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('playlist_item_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('video_thumbnail_time', models.TimeField(default='00:00:00')),
                ('video_status', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(null=True)),
                ('submissiondate', models.DateTimeField(default=datetime.datetime(2000, 1, 2, 12, 0))),
                ('assignment_status', models.PositiveSmallIntegerField(default=0)),
                ('extension_status', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'creation_tutorialresource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tutorial Level',
                'db_table': 'creation_level',
            },
        ),
    ]
