# Generated by Django 3.0.3 on 2022-06-01 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csc',
            old_name='status',
            new_name='activation_status',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('vle', 'csc', 'transcdate')},
        ),
        migrations.AlterUniqueTogether(
            name='vle',
            unique_together={('csc', 'user')},
        ),
    ]
