# Generated by Django 3.0.3 on 2022-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0002_auto_20220601_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tenure',
            field=models.CharField(blank=True, choices=[('quarterly', 'quarterly'), ('biannually', 'biannually'), ('annually', 'annually')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tenure_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
