# Generated by Django 3.0.3 on 2022-07-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
        ('csc', '0003_auto_20220601_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='FossCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(max_length=2)),
                ('is_learners_allowed', models.BooleanField(default=0, max_length=2)),
                ('is_translation_allowed', models.BooleanField(default=0, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_on_homepage', models.PositiveSmallIntegerField(default=0, help_text='0:Series, 1:Display on home page, 2:Archived')),
                ('available_for_nasscom', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for nasscom')),
                ('available_for_jio', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for jio and spoken-tutorial.in')),
                ('csc_dca_programme', models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for csc-dca programme')),
            ],
            options={
                'verbose_name': 'FOSS',
                'verbose_name_plural': 'FOSSes',
                'ordering': ('foss',),
            },
        ),
        migrations.CreateModel(
            name='FossSuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FOSS Category',
                'verbose_name_plural': 'FOSS Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('edu_qualification', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_of_registration', models.DateField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.City')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.District')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vle_id', models.ManyToManyField(to='csc.VLE')),
            ],
        ),
        migrations.CreateModel(
            name='Vle_csc_foss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_type', models.CharField(choices=[('', '-- None --'), ('dca', 'DCA Programme'), ('individual', 'Individual Course')], max_length=100)),
                ('created', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('spoken_foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.FossCategory')),
                ('vle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.VLE')),
            ],
            options={
                'unique_together': {('spoken_foss', 'programme_type')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField()),
                ('ttime', models.TimeField()),
                ('publish', models.BooleanField()),
                ('slug', models.SlugField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note_student', models.TextField(blank=True, null=True)),
                ('note_invigilator', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=252, null=True)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.FossCategory')),
                ('vle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.VLE')),
            ],
        ),
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vle', models.ManyToManyField(to='csc.VLE')),
            ],
        ),
        migrations.CreateModel(
            name='InvigilationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.Invigilator')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.Test')),
            ],
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='category',
            field=models.ManyToManyField(to='csc.FossSuperCategory'),
        ),
        migrations.CreateModel(
            name='Student_Foss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csc_foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.Vle_csc_foss')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.Student')),
            ],
            options={
                'unique_together': {('student', 'csc_foss')},
            },
        ),
    ]
