# Generated by Django 3.0.3 on 2022-07-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0004_vle_csc_foss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vle_csc_foss',
            name='programme_type',
            field=models.CharField(choices=[('', '-- None --'), ('dca', 'DCA Programme'), ('individual', 'Individual Course')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vle_csc_foss',
            name='spoken_foss',
            field=models.IntegerField(),
        ),
    ]
