# Generated by Django 3.0.3 on 2022-09-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0005_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='test_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='studenttest',
            unique_together={('student', 'test')},
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.FossCategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.Student')),
                ('vle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.VLE')),
            ],
        ),
    ]
