# Generated by Django 3.0.3 on 2022-07-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0005_auto_20220711_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vle_csc_foss',
            unique_together={('spoken_foss', 'programme_type')},
        ),
    ]
