# Generated by Django 3.0.3 on 2022-09-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0006_auto_20220901_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiateCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('certificate_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.CertifiateCategories')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.FossCategory')),
            ],
        ),
    ]
