# Generated by Django 3.0.3 on 2022-07-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0007_auto_20220718_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosscategory',
            name='user',
        ),
    ]
