# Generated by Django 3.0.3 on 2022-09-15 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0008_auto_20220912_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_certificate_course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cert', to='csc.Student'),
        ),
    ]
