# Generated by Django 3.0.3 on 2022-09-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0009_auto_20220915_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_certificate_course',
            name='cert_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cert', to='csc.CertifiateCategories'),
        ),
    ]
