# Generated by Django 3.0.3 on 2022-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0010_invigilator_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='invigilator',
            field=models.ManyToManyField(blank=True, null=True, to='csc.Invigilator'),
        ),
    ]
