# Generated by Django 3.0.3 on 2022-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0011_auto_20220718_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
