# Generated by Django 3.0.3 on 2022-07-19 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0012_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='vle',
            field=models.ForeignKey(default=171, on_delete=django.db.models.deletion.CASCADE, to='csc.VLE'),
            preserve_default=False,
        ),
    ]
