# Generated by Django 3.0.3 on 2022-09-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0012_auto_20220920_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_foss',
            name='student_cert_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csc.Student_certificate_course'),
        ),
        migrations.AlterUniqueTogether(
            name='student_foss',
            unique_together={('student', 'csc_foss', 'student_cert_course')},
        ),
    ]
