# Generated by Django 3.0.3 on 2022-09-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0013_auto_20220927_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_foss',
            name='cert_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csc.CertifiateCategories'),
        ),
        migrations.AddField(
            model_name='student_foss',
            name='foss_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student_foss',
            unique_together={('student', 'csc_foss', 'cert_category')},
        ),
        migrations.RemoveField(
            model_name='student_foss',
            name='student_cert_course',
        ),
    ]
