# Generated by Django 3.0.3 on 2022-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0013_auto_20220719_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='note_invigilator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='note_student',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
