# Generated by Django 3.0.3 on 2022-09-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0013_auto_20220927_0844'),
        ('csc', '0014_auto_20220928_1104'),
    ]

    operations = [
    ]
