# Generated by Django 3.0.3 on 2022-07-20 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csc', '0015_invigilator_vle'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilator',
            name='added_by',
            field=models.ForeignKey(default=310, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invigilator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invigilator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
