# Generated by Django 3.0.3 on 2022-07-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0017_invigilationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='invigilator',
        ),
    ]
