# Generated by Django 3.0.3 on 2022-11-21 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0017_auto_20221104_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csctestatttendance',
            unique_together={('mdlcourse_id', 'mdluser_id')},
        ),
    ]
