# Generated by Django 3.0.3 on 2022-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0017_auto_20221006_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='invigilator',
            field=models.ManyToManyField(blank=True, null=True, to='csc.Invigilator'),
        ),
    ]
