# Generated by Django 3.0.3 on 2022-11-21 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0018_auto_20221121_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dca_count',
            field=models.IntegerField(default=0),
        ),
    ]
