# Generated by Django 3.2.4 on 2023-01-03 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0019_auto_20221121_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='publish',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
    ]
