# Generated by Django 3.0.3 on 2022-12-07 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0019_auto_20221121_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='csctestatttendance',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
