# Generated by Django 3.0.3 on 2022-10-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0019_auto_20221006_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='vle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csc.VLE'),
        ),
    ]
