# Generated by Django 3.0.3 on 2023-01-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0020_auto_20221207_1229'),
        ('csc', '0020_auto_20230103_2138'),
    ]

    operations = [
    ]
