# Generated by Django 3.0.3 on 2022-10-07 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0020_auto_20221006_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2022, 10, 7)),
        ),
        migrations.CreateModel(
            name='CSCTestAtttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdluser_firstname', models.CharField(max_length=100)),
                ('mdluser_lastname', models.CharField(max_length=100)),
                ('mdluser_id', models.PositiveIntegerField()),
                ('mdlcourse_id', models.PositiveIntegerField(default=0)),
                ('mdlquiz_id', models.PositiveIntegerField(default=0)),
                ('mdlattempt_id', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('mdlgrade', models.DecimalField(decimal_places=5, default=0.0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csc.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csc.Test')),
            ],
            options={
                'verbose_name': 'Test Attendance',
                'unique_together': {('test', 'mdluser_id')},
            },
        ),
    ]
