# Generated by Django 3.0.3 on 2023-01-16 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0021_merge_20230104_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2023, 1, 16)),
        ),
    ]
