# Generated by Django 3.0.3 on 2022-10-11 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0021_auto_20221007_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
        ),
        migrations.CreateModel(
            name='CSCFossMdlCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdlcourse_id', models.PositiveIntegerField()),
                ('mdlquiz_id', models.PositiveIntegerField()),
                ('foss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainingfoss', to='csc.FossCategory')),
                ('testfoss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testfoss', to='csc.FossCategory')),
            ],
        ),
    ]
