# Generated by Django 3.0.3 on 2022-11-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0021_auto_20221102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilator',
            name='vle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invig', to='csc.VLE'),
            preserve_default=False,
        ),
    ]
