# Generated by Django 3.0.3 on 2022-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0021_auto_20221026_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilator',
            name='password_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
