# Generated by Django 3.0.3 on 2022-10-27 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0022_invigilator_password_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOSSVLEView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.CharField(max_length=256)),
                ('vle_id', models.IntegerField()),
            ],
            options={
                'db_table': 'foss_vle',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='csctestatttendance',
            name='mdluser_firstname',
        ),
        migrations.RemoveField(
            model_name='csctestatttendance',
            name='mdluser_lastname',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
    ]
