# Generated by Django 3.0.3 on 2023-04-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0022_auto_20230116_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vle',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
