# Generated by Django 3.0.3 on 2022-10-27 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csc', '0023_auto_20221027_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invigilator',
            unique_together={('user', 'vle')},
        ),
    ]
