# Generated by Django 3.0.3 on 2022-10-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0022_auto_20221011_1700'),
        ('csc', '0024_auto_20221027_2027'),
    ]

    operations = [
    ]
