# Generated by Django 3.0.3 on 2022-10-28 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0025_merge_20221028_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csctestatttendance',
            name='mdluser_firstname',
        ),
        migrations.RemoveField(
            model_name='csctestatttendance',
            name='mdluser_lastname',
        ),
        migrations.AddField(
            model_name='student',
            name='mdl_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cscfossmdlcourses',
            name='foss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cscfoss', to='csc.FossCategory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
    ]
