# Generated by Django 3.0.3 on 2022-10-31 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0026_auto_20221028_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='note_invigilator',
        ),
        migrations.RemoveField(
            model_name='test',
            name='note_student',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2022, 10, 31)),
        ),
    ]
