# Generated by Django 3.0.3 on 2020-03-03 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blended_workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=255)),
                ('workshop_date', models.DateField()),
                ('workshop_content', models.TextField()),
                ('workshop_logo', models.FileField(blank=True, null=True, upload_to='logos/workshop_logos/')),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=255)),
                ('internship_date', models.DateField()),
                ('internship_desc', models.TextField()),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=255)),
                ('nav_id', models.CharField(max_length=50)),
                ('data_section', models.CharField(max_length=50)),
                ('fa_icon', models.CharField(blank=True, max_length=50)),
                ('back_image', models.FileField(blank=True, null=True, upload_to='page_backgrounds/')),
                ('status', models.BooleanField(default=0)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_url', models.CharField(max_length=300)),
                ('product_description', models.CharField(max_length=1000)),
                ('logo', models.FileField(upload_to='logos/')),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('actual_content', models.TextField()),
                ('minified_content', models.TextField()),
                ('short_description', models.TextField()),
                ('source_title', models.CharField(max_length=200, null=True)),
                ('source_link', models.URLField(null=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testimonial_approved_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonial_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobfair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobfair_title', models.CharField(max_length=255)),
                ('jobfair_date', models.DateField()),
                ('jobfair_desc', models.TextField()),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
                ('companies', models.ManyToManyField(to='spoken.Company')),
            ],
        ),
    ]
