# Generated by Django 2.2.7 on 2019-11-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=100)),
                ('nav_id', models.CharField(max_length=50)),
                ('data_section', models.CharField(max_length=50)),
                ('fa_icon', models.CharField(max_length=50)),
                ('back_image', models.FileField(upload_to='page_backgrounds/')),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
