# Generated by Django 3.0.5 on 2020-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures_jobfair/'),
        ),
    ]
