# Generated by Django 3.0.3 on 2020-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='show',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='source_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
