# Generated by Django 3.0.3 on 2020-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0002_auto_20200303_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.CharField(default='series', max_length=200)),
                ('path', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('workshop_details', models.CharField(default='Workshop', max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Testimonials',
                'verbose_name_plural': 'Media Testimonials',
            },
        ),
    ]
