# Generated by Django 2.2.7 on 2020-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0002_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blended_workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=255)),
                ('workshop_date', models.DateField()),
                ('workshop_content', models.TextField()),
                ('workshop_logo', models.FileField(upload_to='page_backgrounds/workshop_logos/')),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='nav',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='nav',
            name='nav_name',
            field=models.CharField(max_length=255),
        ),
    ]
