# Generated by Django 3.0.3 on 2020-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0003_auto_20200117_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blended_workshops',
            name='workshop_logo',
            field=models.FileField(upload_to='logos/workshop_logos/'),
        ),
    ]
