# Generated by Django 3.0.3 on 2020-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0003_mediatestimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatestimonials',
            name='media',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
