# Generated by Django 3.0.5 on 2020-04-22 11:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0003_jobfair_companies_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='widget_group_ids',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), default='', size=100),
        ),
    ]
