# Generated by Django 3.0.3 on 2020-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0004_auto_20200302_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=255)),
                ('internship_date', models.DateField()),
                ('internship_desc', models.TextField()),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobfair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobfair_title', models.CharField(max_length=255)),
                ('jobfair_date', models.DateField()),
                ('jobfair_desc', models.TextField()),
                ('know_more_link', models.CharField(max_length=300)),
                ('updated', models.DateField(auto_now=True)),
                ('companies', models.ManyToManyField(to='spoken.Company')),
            ],
        ),
    ]
