# Generated by Django 3.0.3 on 2020-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0004_mediatestimonials_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatestimonials',
            name='media',
            field=models.FileField(default='', upload_to='testimonials/'),
        ),
    ]
