# Generated by Django 2.2.7 on 2020-03-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0006_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
