# Generated by Django 3.0.5 on 2020-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0006_jobfair_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jobfair',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='spoken.Company'),
        ),
        migrations.AlterField(
            model_name='jobfair',
            name='companies_csv',
            field=models.FileField(blank=True, default='', null=True, upload_to='companies_csv/'),
        ),
    ]
