# Generated by Django 3.0.5 on 2020-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0007_auto_20200511_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='temp',
        ),
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
