# Generated by Django 2.0 on 2020-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0007_award_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='jobfair_date',
        ),
        migrations.AddField(
            model_name='jobfair',
            name='jobfair_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='jobfair_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='num_students_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='num_students_registered',
            field=models.IntegerField(default=0),
        ),
    ]
