# Generated by Django 2.0 on 2020-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0008_auto_20200327_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jobfair',
            name='eligibility_criteria',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='num_student_appeared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='selection_process',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='technologies',
            field=models.ManyToManyField(to='spoken.Technology'),
        ),
    ]
