# Generated by Django 2.0 on 2020-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0009_auto_20200401_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='jobfair_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
