# Generated by Django 2.0 on 2020-04-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken', '0010_jobfair_jobfair_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='technologies',
            field=models.ManyToManyField(to='spoken.Technology'),
        ),
    ]
