# Generated by Django 3.0.3 on 2023-02-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='full_key',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='key',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
