# Generated by Django 3.0.3 on 2020-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201007_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='completion_status_sent',
            field=models.BooleanField(default=False),
        ),
    ]
